import yfinance as yf
import pandas as pd
import pandas_ta as ta
import plotly.graph_objects as go
from datetime import datetime, timedelta

# ==========================================
# CONFIGURATION / USER INPUTS
# ==========================================
ticker = "RELIANCE.NS"          # Indian Stock Ticker (NSE format: SYMBOL.NS)
timeframe = "1d"               # Timeframe: '15m', '1h', '1d', '1wk'
past_data_days = 365           # How much past data to analyze (Lookback)
volume_multiplier = 1.5         # Volume expansion threshold for breakout

# Calculate start date based on lookback input
start_date = (datetime.now() - timedelta(days=past_data_days)).strftime('%Y-%m-%d')
end_date = datetime.now().strftime('%Y-%m-%d')

print(f"Fetching {ticker} data from {start_date} to {end_date}...")
df = yf.download(ticker, start=start_date, end=end_date, interval=timeframe)

if df.empty:
    raise ValueError("No data retrieved. Verify the ticker symbol or timeframe configuration.")

# Clean multi-index columns if generated by yfinance
df.columns = [col[0] if isinstance(col, tuple) else col for col in df.columns]

# ==========================================
# 1. MARKET STRUCTURE ANALYSIS
# ==========================================
# Use local rolling maximums/minimums to determine Swings (Left/Right bars = 5)
window = 5
df['Swing_High'] = df['High'][(df['High'] == df['High'].rolling(window=window*2+1, center=True).max())]
df['Swing_Low'] = df['Low'][(df['Low'] == df['Low'].rolling(window=window*2+1, center=True).min())]

# Forward fill last structural high/low to determine Market Structure Shift (MSS)
df['Last_SH'] = df['Swing_High'].ffill()
df['Last_SL'] = df['Swing_Low'].ffill()

current_close = df['Close'].iloc[-1]
last_sh = df['Last_SH'].dropna().iloc[-1] if not df['Last_SH'].dropna().empty else float('inf')
last_sl = df['Last_SL'].dropna().iloc[-1] if not df['Last_SL'].dropna().empty else float('-inf')

structure_trend = "Sideways"
if current_close > last_sh:
    structure_trend = "Bullish (MSS)"
elif current_close < last_sl:
    structure_trend = "Bearish (MSS)"

# ==========================================
# 2. SUPPORT & RESISTANCE (Rule A, B, C, D)
# ==========================================
# Collect all historical valid swing highs and lows
all_levels = pd.concat([df['Swing_High'].dropna(), df['Swing_Low'].dropna()]).tolist()

closest_sup = None
closest_res = None
min_sup_diff = float('inf')
min_res_diff = float('inf')

# Rule D Filter: Locate levels immediate below/above the current closing price
for level in all_levels:
    if level < current_close and (current_close - level) < min_sup_diff:
        min_sup_diff = current_close - level
        closest_sup = level
    elif level > current_close and (level - current_close) < min_res_diff:
        min_res_diff = level - current_close
        closest_res = level

# ==========================================
# 3. BREAKOUT OR BREAKDOWN
# ==========================================
df['Vol_MA'] = ta.sma(df['Volume'], length=20)
df['High_Vol'] = df['Volume'] > (df['Vol_MA'] * volume_multiplier)

df['Breakout'] = False
df['Breakdown'] = False

if closest_res:
    df['Breakout'] = (df['Close'] > closest_res) & (df['Close'].shift(1) <= closest_res) & df['High_Vol']
if closest_sup:
    df['Breakdown'] = (df['Close'] < closest_sup) & (df['Close'].shift(1) >= closest_sup) & df['High_Vol']

# ==========================================
# 4. PRICE HOLD OR PRICE REJECT (Candlestick Patterns)
# ==========================================
body = (df['Close'] - df['Open']).abs()
total_range = df['High'] - df['Low']
upper_shadow = df['High'] - df[['Open', 'Close']].max(axis=1)
lower_shadow = df[['Open', 'Close']].min(axis=1) - df['Low']

# Pattern Definitions
df['Hammer'] = (lower_shadow > (body * 2)) & (upper_shadow < (body * 0.5)) & (df['Low'] <= closest_sup * 1.002 if closest_sup else False)
df['Shooting_Star'] = (upper_shadow > (body * 2)) & (lower_shadow < (body * 0.5)) & (df['High'] >= closest_res * 0.998 if closest_res else False)

# ==========================================
# 5. CHART VISUALIZATION (Interactive Dashboard)
# ==========================================
fig = go.Figure()

# Plot Candlesticks
fig.add_trace(go.Candlestick(
    x=df.index, open=df['Open'], high=df['High'], low=df['Low'], close=df['Close'],
    name="Price Action"
))

# Plot Dynamic Near-Price S&R Levels (Rule D Line Mapping)
if closest_res:
    fig.add_shape(type="line", x0=df.index[0], y0=closest_res, x1=df.index[-1], y1=closest_res,
                  line=dict(color="Red", width=2, dash="dash"), name="Near Resistance")
if closest_sup:
    fig.add_shape(type="line", x0=df.index[0], y0=closest_sup, x1=df.index[-1], y1=closest_sup,
                  line=dict(color="Green", width=2, dash="dash"), name="Near Support")

# Marker Plotting for Institutional Breakouts
breakouts = df[df['Breakout']]
fig.add_trace(go.Scatter(x=breakouts.index, y=breakouts['Low'] * 0.99, mode='markers',
                         marker=dict(symbol='triangle-up', size=12, color='green'), name='Volume Breakout'))

breakdowns = df[df['Breakdown']]
fig.add_trace(go.Scatter(x=breakdowns.index, y=breakdowns['High'] * 1.01, mode='markers',
                         marker=dict(symbol='triangle-down', size=12, color='red'), name='Volume Breakdown'))

# Marker Plotting for Candle Rejections at Key Levels
hammers = df[df['Hammer']]
fig.add_trace(go.Scatter(x=hammers.index, y=hammers['Low'] * 0.98, mode='markers+text', text="Hammer",
                         textposition="bottom center", marker=dict(symbol='circle', size=8, color='emerald'), name='Hammer rejection'))

stars = df[df['Shooting_Star']]
fig.add_trace(go.Scatter(x=stars.index, y=stars['High'] * 1.02, mode='markers+text', text="Star",
                         textposition="top center", marker=dict(symbol='circle', size=8, color='maroon'), name='Shooting Star rejection'))

# Design layout properties
fig.update_layout(
    title=f"{ticker} Analysis Framework | Market Bias: {structure_trend}",
    yaxis_title="Stock Price (INR)",
    xaxis_title="Timeline",
    xaxis_rangeslider_visible=False,
    template="plotly_dark"
)

fig.show()
